name: siac-dev

channels:
  - conda-forge

dependencies:
  - python=3.6*
  - gdal=2.3.3
  - numpy>=1.13
  - scipy=1.0
  - psutil
  - six
  - lightgbm=2.1.0
  - requests
  - scikit-learn
  - scikit-image
